apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nearby

resources:
  - namespace.yaml
  - elasticsearch.yaml
  - qdrant.yaml
  - postgis.yaml
  - search-api.yaml
  - indexer-batch.yaml
  - backend-wiring.yaml
  - komoran-dict.configmap.yaml
