apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: nearby
  region: ap-northeast-2

availabilityZones: ["ap-northeast-2b", "ap-northeast-2c", "ap-northeast-2d"]

iam:
  withOIDC: true

vpc:
  nat:
    gateway: Disable

addons:
  - name: aws-ebs-csi-driver
    wellKnownPolicies:
      ebsCSIController: true

managedNodeGroups:
  - name: ng-query
    instanceType: m7i.xlarge
    desiredCapacity: 1
    minSize: 1
    maxSize: 1
    availabilityZones: ["ap-northeast-2b"]
    volumeSize: 50
    labels:
      role: query
    privateNetworking: false
    tags:
      purpose: nearby-latency-experiment

  - name: ng-index
    instanceType: c7i.2xlarge
    desiredCapacity: 1
    minSize: 1
    maxSize: 1
    volumeSize: 50
    availabilityZones: ["ap-northeast-2b"]
    labels:
      role: index
    privateNetworking: false
    tags:
      purpose: nearby-latency-experiment
