apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - target: { kind: StatefulSet, name: elasticsearch }
    patch: |
      - op: replace
        path: /spec/template/spec/containers/0/env/2/value
        value: "-Xms512m -Xmx512m"
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: "768Mi"
